# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LoadImage' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LoadImage

  pod 'SDWebImage'
  pod 'YYImage'
  target 'LoadImageTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LoadImageUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
